[tool.poetry]
name = "tft"
version = "0.1.0"
description = "Test project for trading system"
authors = ["Maxim <nkvmaxim@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.*"
numpy = "1.23.5"
ta = "^0.11"
matplotlib = "^3.8"
seaborn = "^0.13"
torch = "1.13.1"
pandas = "1.5.3"
pyarrow = "^20.0.0"
pytorch-forecasting = "0.10.3"
pytorch-lightning = "1.5.10"
scikit-learn = "1.1.3"
vectorbt = "^0.28.0"
xgboost = "^2.0.3"
typer = "^0.16.0"

[tool.poetry.group.dev.dependencies]
jupyterlab = "^4.4.4"
ipykernel = "^6.29.5"
ipywidgets = "^8.1.7"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
tft-train = "tft.tft.train.train_tft:app"
tft-train-xgb-tft = "tft.tft.train.train_xgb_tft:app"
tft-train-inverted-tft = "tft.tft.train.train_inverted_tft:app"

