[tool.poetry]
name = "core"
version = "0.1.0"
description = "Modular trading-system pipeline (ML, MLOps, HF Space)"
authors = ["maxim"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
pandas        = "^2.3"
ta            = ">=0.11,<1.0"
yfinance      = "^0.2.64"
hydra-core    = "^1.3"
pydantic      = "^2.11"
scikit-learn  = ">=1.3,<2.0"
tensorflow     = "~2.17"
pyarrow = {version = "^20.0.0", extras = ["parquet"]}
cmdstanpy = "^1.2.5"
orbit-ml = "^1.1.4.9"
typer = "^0.16.0"
plotly = "^6.2.0"
ipywidgets = "^8.1.7"
torch = {version = "2.2.0", extras = ["cpu"]}
pytorch-forecasting = "1.4.0"
pytorch-lightning = "^2.5.2"

[tool.poetry.group.dev.dependencies]
jupyterlab = "^4.4"
ipykernel  = "^6.29"
black      = "^24.4"
isort      = "^5.13"
flake8     = "^7.0"
mypy       = "^1.10"
pre-commit = "^3.7"
pytest     = "^8.2"
great-expectations = "^0.18"
great-expectations = ">=0.18,<1.0"
matplotlib = "^3.10.3"
seaborn = "^0.13.2"

[tool.poetry.scripts]
tradingbot = "tradingbot.cli:app"
tradingbot-pipeline = "tradingbot.pipeline:_cli"
make-features = "core.feature_engineering.make_features:main"

[build-system]
requires = ["poetry-core>=1.8,<2"]
build-backend = "poetry.core.masonry.api"
